// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/product_adm/product_adm.go
//
// Generated by this command:
//
//	mockgen -source=usecase/product_adm/product_adm.go -destination=mocks/usecase_mocks/product_adm.go -package=usecase_mocks
//

// Package usecase_mocks is a generated GoMock package.
package usecase_mocks

import (
	context "context"
	reflect "reflect"

	product_service "github.com/private-project-pp/pos-grpc-contract/model/product_service"
	gomock "go.uber.org/mock/gomock"
)

// MockProductAdministration is a mock of ProductAdministration interface.
type MockProductAdministration struct {
	ctrl     *gomock.Controller
	recorder *MockProductAdministrationMockRecorder
	isgomock struct{}
}

// MockProductAdministrationMockRecorder is the mock recorder for MockProductAdministration.
type MockProductAdministrationMockRecorder struct {
	mock *MockProductAdministration
}

// NewMockProductAdministration creates a new mock instance.
func NewMockProductAdministration(ctrl *gomock.Controller) *MockProductAdministration {
	mock := &MockProductAdministration{ctrl: ctrl}
	mock.recorder = &MockProductAdministrationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductAdministration) EXPECT() *MockProductAdministrationMockRecorder {
	return m.recorder
}

// AddNewProductIntoWarehouse mocks base method.
func (m *MockProductAdministration) AddNewProductIntoWarehouse(ctx context.Context, in *product_service.UpsertProductWarehouseRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewProductIntoWarehouse", ctx, in)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNewProductIntoWarehouse indicates an expected call of AddNewProductIntoWarehouse.
func (mr *MockProductAdministrationMockRecorder) AddNewProductIntoWarehouse(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewProductIntoWarehouse", reflect.TypeOf((*MockProductAdministration)(nil).AddNewProductIntoWarehouse), ctx, in)
}

// AddNewProductUnit mocks base method.
func (m *MockProductAdministration) AddNewProductUnit(ctx context.Context, in *product_service.UpsertUnitRequest) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewProductUnit", ctx, in)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddNewProductUnit indicates an expected call of AddNewProductUnit.
func (mr *MockProductAdministrationMockRecorder) AddNewProductUnit(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewProductUnit", reflect.TypeOf((*MockProductAdministration)(nil).AddNewProductUnit), ctx, in)
}

// AddingNewProduct mocks base method.
func (m *MockProductAdministration) AddingNewProduct(ctx context.Context, in *product_service.AddProductRequest) (*product_service.AddProductResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddingNewProduct", ctx, in)
	ret0, _ := ret[0].(*product_service.AddProductResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddingNewProduct indicates an expected call of AddingNewProduct.
func (mr *MockProductAdministrationMockRecorder) AddingNewProduct(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddingNewProduct", reflect.TypeOf((*MockProductAdministration)(nil).AddingNewProduct), ctx, in)
}

// UpdateExistingProductInWarehouse mocks base method.
func (m *MockProductAdministration) UpdateExistingProductInWarehouse(ctx context.Context, in *product_service.UpsertProductWarehouseRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExistingProductInWarehouse", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExistingProductInWarehouse indicates an expected call of UpdateExistingProductInWarehouse.
func (mr *MockProductAdministrationMockRecorder) UpdateExistingProductInWarehouse(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExistingProductInWarehouse", reflect.TypeOf((*MockProductAdministration)(nil).UpdateExistingProductInWarehouse), ctx, in)
}

// UpdateExistingUnit mocks base method.
func (m *MockProductAdministration) UpdateExistingUnit(in *product_service.UpsertUnitRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExistingUnit", in)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExistingUnit indicates an expected call of UpdateExistingUnit.
func (mr *MockProductAdministrationMockRecorder) UpdateExistingUnit(in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExistingUnit", reflect.TypeOf((*MockProductAdministration)(nil).UpdateExistingUnit), in)
}

// UpsertProductIntoWarehouse mocks base method.
func (m *MockProductAdministration) UpsertProductIntoWarehouse(ctx context.Context, in *product_service.UpsertProductWarehouseRequest) (*product_service.UpsertProductWarehouseResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertProductIntoWarehouse", ctx, in)
	ret0, _ := ret[0].(*product_service.UpsertProductWarehouseResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertProductIntoWarehouse indicates an expected call of UpsertProductIntoWarehouse.
func (mr *MockProductAdministrationMockRecorder) UpsertProductIntoWarehouse(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertProductIntoWarehouse", reflect.TypeOf((*MockProductAdministration)(nil).UpsertProductIntoWarehouse), ctx, in)
}

// UpsertUnit mocks base method.
func (m *MockProductAdministration) UpsertUnit(ctx context.Context, in *product_service.UpsertUnitRequest) (*product_service.UpsertUnitResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertUnit", ctx, in)
	ret0, _ := ret[0].(*product_service.UpsertUnitResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpsertUnit indicates an expected call of UpsertUnit.
func (mr *MockProductAdministrationMockRecorder) UpsertUnit(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertUnit", reflect.TypeOf((*MockProductAdministration)(nil).UpsertUnit), ctx, in)
}
